name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          # Ставим проект с extras для веба и разработки
          pip install -e ".[web,dev]"
          # Страховка: если extras не подтянулись (разные версии pip/PEP 621 и т.д.)
          pip install --upgrade --upgrade-strategy eager ruff black pytest

      - name: Show versions
        run: |
          python --version
          pip --version
          ruff --version
          black --version
          pytest --version

      - name: Lint (ruff)
        run: ruff check hhcli

      - name: Format check (black)
        run: black --check hhcli

      - name: Run tests (pytest)
        run: pytest -q
